Exploratory Data Analysis

Understanding the dataset to explore how the data is present in the dataset.

In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [4]:
# Creating a connection with the database
engine  = create_engine("mysql+pymysql://root:%40Vasvikas83@localhost/q2c")

In [5]:
# Checking tables present in the database
tables = pd.read_sql("SHOW TABLES", con = engine)
tables

      Tables_in_q2c
0       collections
1         contracts
2         cpq_quote
3  customer_summary
4            events
5          invoices
6          payments
7    pricing_master
8     subscriptions

In [6]:
pd.read_sql("Select count(*) from cpq_quote", engine)

   count(*)
0     41786

In [7]:
for table in tables.iloc[:, 0]:
    print("-"*50, table, "-"*50)

    count = pd.read_sql(
        f"SELECT count(*) as count FROM {table}",
        con=engine
    )["count"].values[0]

    print("Count of records:", count)
    display(pd.read_sql(f"SELECT * FROM {table} LIMIT 10", con=engine))

-------------------------------------------------- collections --------------------------------------------------
Count of records: 12385

,collection_id,invoice_id,customer_id,collection_date,amount_collected,collection_status
0,COL1,INV35714,C22913,2024-01-26,0.00,Unrecovered
1,COL2,INV4953,C3244,2024-01-21,583.74,Recovered
2,COL3,INV24545,C15869,2024-01-20,0.00,Unrecovered
3,COL4,INV47066,C30313,2024-01-13,0.00,Unrecovered
4,COL5,INV57214,C37151,2024-01-30,0.00,Unrecovered
5,COL6,INV7374,C4834,2024-01-09,635.76,Recovered
6,COL7,INV21262,C13838,2024-01-13,754.58,Recovered
7,COL8,INV2760,C1777,2024-01-21,397.02,Recovered
8,COL9,INV35801,C22940,2024-01-31,1468.44,Recovered
9,COL10,INV36049,C23087,2024-01-25,0.00,Unrecovered

-------------------------------------------------- contracts --------------------------------------------------
Count of records: 13769

,contract_id,quote_id,customer_id,plan_id,billing_type,contract_start_date,final_price,discount_percent,discount_end_date,contract_status,version,contract_end_date,parent_contract_id
0,CT1,Q4,C4,BY,Yearly,2024-02-16,3960.0,1,2024-03-15 00:00:00,Active,1,None,None
1,CT2,Q6,C6,PY,Yearly,2024-02-27,10000.0,0,2024-03-25 00:00:00,Active,1,None,None
2,CT3,Q8,C8,BM,Monthly,2024-03-01,380.0,5,2024-03-29 00:00:00,Terminated,1,2024-05-01 00:00:00,None
3,CT4,Q11,C11,BY,Yearly,2024-01-31,3800.0,5,2024-02-26 00:00:00,Active,1,None,None
4,CT5,Q16,C16,BM,Monthly,2024-02-23,360.0,10,2024-03-21 00:00:00,Active,1,None,None
5,CT6,Q17,C17,PY,Yearly,2024-01-20,9500.0,5,2024-02-15 00:00:00,Active,1,None,None
6,CT7,Q22,C22,BM,Monthly,2024-01-22,364.0,9,2024-02-18 00:00:00,Active,1,None,None
7,CT8,Q24,C24,PY,Yearly,2024-01-07,8900.0,11,2024-02-02 00:00:00,Active,1,None,None
8,CT9,Q28,C28,PM,Monthly,2024-01-25,860.0,14,2024-02-22 00:00:00,Terminated,1,2024-05-25 00:00:00,None
9,CT10,Q30,C30,PY,Yearly,2024-01-14,8600.0,14,2024-02-10 00:00:00,Active,1,None,None

-------------------------------------------------- cpq_quote --------------------------------------------------
Count of records: 41786

,quote_id,customer_id,plan_id,list_price,discount_percent,discount_start_date,discount_end_date,final_price,quote_date,status,quote_end_date
0,Q1,C1,BY,4000,7,2024-01-22,2024-02-21 00:00:00,3720.0,2024-01-22,Draft,None
1,Q2,C2,PY,10000,0,2024-01-02,2024-02-01 00:00:00,10000.0,2024-01-02,Draft,None
2,Q3,C3,BM,400,10,2024-01-04,2024-02-03 00:00:00,360.0,2024-01-04,Approved,None
3,Q4,C4,BY,4000,1,2024-02-14,2024-03-15 00:00:00,3960.0,2024-02-14,Converted,None
4,Q5,C5,BY,4000,10,2024-01-13,2024-02-12 00:00:00,3600.0,2024-01-13,Approved,None
5,Q6,C6,PY,10000,0,2024-02-24,2024-03-25 00:00:00,10000.0,2024-02-24,Converted,None
6,Q7,C7,BM,400,3,2024-02-01,2024-03-02 00:00:00,388.0,2024-02-01,Draft,None
7,Q8,C8,BM,400,5,2024-02-28,2024-03-29 00:00:00,380.0,2024-02-28,Amended,2024-05-01 00:00:00
8,Q9,C9,BY,4000,4,2024-01-22,2024-02-21 00:00:00,3840.0,2024-01-22,Rejected,None
9,Q10,C10,PM,1000,12,2024-01-25,2024-02-24 00:00:00,880.0,2024-01-25,Approved,None

-------------------------------------------------- customer_summary --------------------------------------------------
Count of records: 11983

  customer_id   amount
0       C1000   3600.0
1      C10001   3920.0
2      C10009   3600.0
3      C10011   3600.0
4      C10012   2388.0
5      C10013   9600.0
6      C10018   3600.0
7      C10019   9600.0
8      C10022   4764.0
9      C10025  12760.0

-------------------------------------------------- events --------------------------------------------------
Count of records: 6001

  subscription_id event_type month plan_id start_month end_month
0              S2  downgrade   6.0      BM
1              S3  downgrade   7.0      BM
2              S4      pause                       3.0       5.0
3              S5      pause                       5.0       7.0
4              S7  downgrade   4.0      BM
5             S10      pause                       3.0       4.0
6             S13  downgrade   3.0      BM
7             S13      pause                       3.0       5.0
8             S17  downgrade   7.0      BM
9             S17      pause                       5.0       6.0

-------------------------------------------------- invoices --------------------------------------------------
Count of records: 82991

  invoice_id subscription_id customer_id plan_id invoice_date  amount
0   INV16362           S3156      C10690      BY   2024-01-02  3600.0
1   INV30163           S5758      C19319      PM   2024-01-02   860.0
2   INV35714           S6840      C22913      PY   2024-01-02  9500.0
3   INV36160           S6917      C23133      BY   2024-01-02  3960.0
4   INV37967           S7275      C24324      BY   2024-01-02  3680.0
5    INV4953            S974       C3244      PM   2024-01-02   970.0
6     INV851            S187        C623      BY   2024-01-02  3760.0
7   INV15972           S3083      C10460      PM   2024-01-03   900.0
8   INV17644           S3380      C11468      PM   2024-01-03   990.0
9    INV2204            S436       C1404      PM   2024-01-03   900.0

-------------------------------------------------- payments --------------------------------------------------
Count of records: 82991

  payment_id invoice_id customer_id payment_date  amount_paid payment_status
0       PAY1   INV16362      C10690   2024-01-08      3600.00           Paid
1       PAY2   INV30163      C19319   2024-01-03       860.00           Paid
2       PAY3   INV35714      C22913   2024-01-11      5483.26        Partial
3       PAY4   INV36160      C23133   2024-01-16      3960.00           Late
4       PAY5   INV37967      C24324   2024-01-04      3680.00           Paid
5       PAY6    INV4953       C3244         None         0.00         Failed
6       PAY7     INV851        C623   2024-01-14      3760.00           Late
7       PAY8   INV15972      C10460   2024-01-08       900.00           Paid
8       PAY9   INV17644      C11468   2024-01-12       990.00           Paid
9      PAY10    INV2204       C1404   2024-01-19       900.00           Late

-------------------------------------------------- pricing_master --------------------------------------------------
Count of records: 4

,plan_id,plan_name,billing_type,list_price,currency,is_active,max_discount_percent
0,BM,Base,Monthly,400,USD,1,10
1,PM,Pro,Monthly,1000,USD,1,25
2,BY,Base,Yearly,4000,USD,1,10
3,PY,Pro,Yearly,10000,USD,1,15

-------------------------------------------------- subscriptions --------------------------------------------------
Count of records: 13769

,subscription_id,contract_id,customer_id,plan_id,billing_type,subscription_start_date,subscription_status
0,S1,CT1,C4,BY,Yearly,2024-02-16,Active
1,S2,CT2,C6,PY,Yearly,2024-02-27,Active
2,S3,CT3,C8,BM,Monthly,2024-03-01,Active
3,S4,CT4,C11,BY,Yearly,2024-01-31,Active
4,S5,CT5,C16,BM,Monthly,2024-02-23,Active
5,S6,CT6,C17,PY,Yearly,2024-01-20,Active
6,S7,CT7,C22,BM,Monthly,2024-01-22,Active
7,S8,CT8,C24,PY,Yearly,2024-01-07,Active
8,S9,CT9,C28,PM,Monthly,2024-01-25,Active
9,S10,CT10,C30,PY,Yearly,2024-01-14,Active

In [8]:
""" Here first we bring the pricing_master and cpq_quote table together  
 to verify that discount which are given is within the range and if not those customer_id will be flagged"""

df = pd.read_sql("""SELECT 
    q.quote_id,
    q.customer_id,
    q.plan_id,

    q.discount_percent,
    p.max_discount_percent,

    CASE 
        WHEN q.discount_percent <= p.max_discount_percent 
        THEN 'VALID'
        ELSE 'VIOLATION'
    END AS status

FROM cpq_quote q
JOIN pricing_master p 
    ON q.plan_id = p.plan_id""", con=engine)
df

,quote_id,customer_id,plan_id,discount_percent,max_discount_percent,status
0,Q1,C1,BY,7,10,VALID
1,Q2,C2,PY,0,15,VALID
2,Q3,C3,BM,10,10,VALID
3,Q4,C4,BY,1,10,VALID
4,Q5,C5,BY,10,10,VALID
...,...,...,...,...,...,...
41781,AQ_S11962,C39929,PM,0,25,VALID
41782,AQ_S11963,C39930,PY,0,15,VALID
41783,AQ_S11970,C39955,PM,0,25,VALID
41784,AQ_S11972,C39976,PY,0,15,VALID
41785,AQ_S11976,C39982,PM,0,25,VALID

In [9]:
result = pd.read_sql("""
SELECT 
    SUM(CASE WHEN q.discount_percent <= p.max_discount_percent THEN 1 ELSE 0 END) AS valid_count,
    SUM(CASE WHEN q.discount_percent > p.max_discount_percent THEN 1 ELSE 0 END) AS violation_count
FROM cpq_quote q
JOIN pricing_master p 
    ON q.plan_id = p.plan_id
""", con=engine)

result
df
df["status"].value_counts()

status
VALID    41786
Name: count, dtype: int64

So its conclude that that discount which is given are within the range.
Let's see the quote vs contract. For this time we are going  to those customer who are converted to the contract. also we will verify that any coustomer with the wrong status enter to the contract and if yes then those customer will be Flagged.

In [10]:
df = pd.read_sql("""SELECT * from cpq_quote""", con=engine)
df
df["status"].value_counts()

status
Approved     11995
Converted    11983
Rejected      8045
Draft         7977
Amended       1786
Name: count, dtype: int64

Draft      → nothing  
Approved   → waiting  
Converted  → NEW contract  
Amended    → MODIFY existing contract  
Rejected   → dead

Only those quote whose ststus is Converted and Amended will be in the contract and rest of them should not be present in the contract. We will verify if any quote_id whose status was draft , approved and rejected found in the contract then those quote_id will be flagged.

In [11]:
"""--------------------------------Data Integrity Check-----------------------------------"""


df = pd.read_sql("""SELECT 
    c.contract_id,
    c.customer_id,
    c.quote_id,
    q.status AS quote_status

FROM contracts c
JOIN cpq_quote q 
    ON c.quote_id = q.quote_id

WHERE q.status IN ('Draft', 'Approved', 'Cancelled')
""", con=engine)
df

Empty DataFrame
Columns: [contract_id, customer_id, quote_id, quote_status]
Index: []

So its Conclude that 0 quote_id whose status was "draft", "Approved", "Cancelled" are in the contract. 

Now we will check for the valid quote_id which should in the contract data.
Converted quote → MUST have contract  
If not → broken pipeline

In [12]:
df = pd.read_sql("""SELECT 
    q.quote_id,
    q.customer_id,
    q.status

FROM cpq_quote q
LEFT JOIN contracts c 
    ON q.quote_id = c.quote_id

WHERE q.status = 'Converted'
  AND c.contract_id IS NULL;
""", con=engine)

df

Empty DataFrame
Columns: [quote_id, customer_id, status]
Index: []

So all quote_id which are converted are present in the contract, now we check does all quote_id present in the contract does this exist in the quote table or not. If not then those quote_id present in the contract will be flagged.

In [13]:
"""----------------------------------Referential integrity validation--------------------------------------------"""


df = pd.read_sql("""SELECT 
    c.contract_id,
    c.customer_id,
    c.quote_id

FROM contracts c
LEFT JOIN cpq_quote q 
    ON c.quote_id = q.quote_id

WHERE q.quote_id IS NULL; """, con=engine)
df

Empty DataFrame
Columns: [contract_id, customer_id, quote_id]
Index: []

So its verify that there is no Orphan contract is created.
Now we check there is any duplicate exist or not in the quote and the contract table

In [14]:
"""----------------------------------Duplicate records check--------------------------------------------"""
"""-------------------------------------cpq_quote table-------------------------------------"""
df = pd.read_sql("""SELECT 
    quote_id,
    COUNT(*) AS cnt
FROM cpq_quote
GROUP BY quote_id
HAVING COUNT(*) > 1;""", con=engine)
df

Empty DataFrame
Columns: [quote_id, cnt]
Index: []

In [15]:
"""----------------------------------Duplicate records check--------------------------------------------"""
"""-------------------------------------Contracts table-------------------------------------"""

df = pd.read_sql("""SELECT 
    contract_id,
    COUNT(*) AS cnt
FROM contracts
GROUP BY contract_id
HAVING COUNT(*) > 1;""", con=engine)
df

Empty DataFrame
Columns: [contract_id, cnt]
Index: []

So there is No duplicate present in the quote and contract table.
Now we check weather the dicount which is given in the quote does is match the contract dicount table or not if not
those contract will be marked.

In [16]:
"""-----------------------pricing consistency check between quote and contract-----------------------------"""

df = pd.read_sql("""SELECT 
    c.contract_id,
    c.customer_id,
    c.quote_id,

    q.discount_percent AS quote_discount,
    c.discount_percent AS contract_discount,

    CASE 
        WHEN q.discount_percent = c.discount_percent THEN 'MATCH'
        ELSE 'MISMATCH'
    END AS discount_flag

FROM contracts c
JOIN cpq_quote q 
    ON c.quote_id = q.quote_id

WHERE q.status = 'Converted'
  AND (q.discount_percent <> c.discount_percent 
       OR q.discount_percent IS NULL 
       OR c.discount_percent IS NULL);""", con=engine)
df

Empty DataFrame
Columns: [contract_id, customer_id, quote_id, quote_discount, contract_discount, discount_flag]
Index: []

So this proof that in the contract discount is given the same as per the quote table show.
Now we go to the Contract Vs Subscriptions

In [17]:
"""First e check weather these is any duplicate present in the Subscription table. Subscription_id is a 
primary key in the subscription """

df = pd.read_sql("""SELECT 
    subscription_id,
    COUNT(*) AS cnt
FROM subscriptions
GROUP BY subscription_id
HAVING COUNT(*) > 1;""", con=engine)
df

Empty DataFrame
Columns: [subscription_id, cnt]
Index: []

So this proof that no duplicate present in the subscription table, 
Now we align the contract and subscription table and sgo for the acive subscription.

In [18]:
df = pd.read_sql("""SELECT 
    c.contract_id,
    s.subscription_id,
    s.subscription_status
FROM contracts c
JOIN subscriptions s 
    ON c.contract_id = s.contract_id
WHERE s.subscription_status = 'Active';""", con=engine)
df

         contract_id subscription_id subscription_status
0                CT1              S1              Active
1                CT2              S2              Active
2                CT3              S3              Active
3                CT4              S4              Active
4                CT5              S5              Active
...              ...             ...                 ...
13764  CT_NEW_S11962    S_NEW_S11962              Active
13765  CT_NEW_S11963    S_NEW_S11963              Active
13766  CT_NEW_S11970    S_NEW_S11970              Active
13767  CT_NEW_S11972    S_NEW_S11972              Active
13768  CT_NEW_S11976    S_NEW_S11976              Active

[13769 rows x 3 columns]

Now Let's see How many active contracts have NO subscription?

In [19]:
df = pd.read_sql("""SELECT 
    c.contract_id
FROM contracts c
LEFT JOIN subscriptions s 
    ON c.contract_id = s.contract_id
WHERE c.contract_status = 'Active'
  AND s.subscription_id IS NULL;""", con=engine)
df

Empty DataFrame
Columns: [contract_id]
Index: []

So there are No subscription id where subscrtipion id is null.
Now Le's see Is any contract being billed twice?

In [20]:
df = pd.read_sql("""SELECT 
    contract_id,
    COUNT(*) AS active_subscriptions
FROM subscriptions
WHERE subscription_status = 'Active'
GROUP BY contract_id
HAVING COUNT(*) > 1;""", con = engine)
df

Empty DataFrame
Columns: [contract_id, active_subscriptions]
Index: []

No contract is being billed twice.
Let's see the status mismtch